services:
  novnc:
    build: .
    platform: linux/amd64
    container_name: novnc
    ports:
      - "6080:6080"
      - "11345:11345" 
    environment:
      RESOLUTION: "1920x1080"
      START_GAZEBO: "1"
    volumes:
      - main_volume:/workspace
      - gazebo_models:/root/.gazebo
    restart: unless-stopped

volumes:
  main_volume:
  gazebo_models:
