services:
  novnc:
    build: .
    container_name: novnc
    ports:
      - "6080:6080"
    environment:
      RESOLUTION: "1920x1080"
    volumes:
      - main_volume:/workspace
    restart: unless-stopped

volumes:
  main_volume:
